# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"getHTMLsfu": "00_web_scraping.ipynb",
         "back": "01_data.ipynb",
         "getCredentials": "00_web_scraping.ipynb",
         "getInfo": "01_data.ipynb",
         "getDatosSfu": "00_web_scraping.ipynb",
         "sfuScv": "00_web_scraping.ipynb",
         "web_scraping": "00_web_scraping.ipynb",
         "main": "01_data.ipynb",
         "downloadpth": "01_data.ipynb",
         "loadmodel": "01_data.ipynb"}

modules = ["web_scraping.py",
           "data.py"]

doc_url = "https://Miguel-Antonm.github.io/deploy_DL_space_weather_forecast/"

git_url = "https://github.com/Miguel-Antonm/deploy_DL_space_weather_forecast/tree/master/"

def custom_doc_links(name): return None
