# AUTOGENERATED! DO NOT EDIT! File to edit: 00_web_scraping.ipynb (unless otherwise specified).

__all__ = ['getHTMLsfu', 'back', 'getCredentials', 'getDatosSfu', 'sfuScv', 'main']

# Cell
import random
from time import sleep
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
import datetime
import re
import csv
import os

# Cell
def getHTMLsfu():

    source_code=""
    try:
        rutadriver=back()
        rutadriver=str(rutadriver)+"geckodriver"
        driver = webdriver.Firefox(executable_path=str(rutadriver))
        currentday = datetime.datetime.now()driver.get("https://esc.cbk.waw.pl/products/api.php?parameter=f10_7&start_date="+str(currentday.year-1)+"%2F"+str(currentday.month)+"%2F"+str(currentday.day)+"+00%3A00&end_date="+str(currentday.year)+"%2F"+str(currentday.month)+"%2F"+str(currentday.day)+"+00%3A00&output_type=html")
        sleep(random.uniform(8.0,10.0))


        user = driver.find_element_by_name("callback_0")
        password = driver.find_element_by_name("callback_1")
        button = driver.find_element_by_name("callback_2")

        credentials=getCredentials()
        user.send_keys(credentials[0])
        password.send_keys(credentials[1])
        button.click()
        sleep(random.uniform(10.0,12.0))

        elem = driver.find_element_by_xpath("//*")
        source_code = elem.get_attribute("outerHTML")

    finally:
        driver.quit()
    return source_code





# Cell
def back():
    path=os.getcwd()
    s=path.split('/')
    length=len(s)
    for pathpart in range(0,length-1):
        if pathpart==0:
            back_path=s[pathpart]+"/"
        else:
            back_path=back_path+s[pathpart]+"/"
    return str(back_path)


# Cell
def getCredentials():
    try:
        credentials=[]
        rutatxt=back()
        rutatxt=str(rutatxt)+"/infouser.txt"
        f = open (rutatxt,'r')
        mensaje = f.read()
        user=re.findall("usuario='(.*?)'",mensaje)[0]
        password=re.findall("password='(.*?)'",mensaje)[0]
        credentials.append(user)
        credentials.append(password)

    finally:
        f.close()
    return credentials

# Cell
def getDatosSfu(html):
    sfudiario=re.findall('<tr>\n<td>(.*?)/td></tr>',str(html),re.DOTALL)
    listaDatos=[]
    for dia in sfudiario:
        datofecha=re.findall("(.*?)</td>",dia)
        datosfu=re.findall("<td>(.*?)<",dia)
        listaDatos.append([datofecha[0],datosfu[0]])
    return listaDatos

# Cell
def sfuScv(listaDatos):
    currentday = datetime.datetime.now()
    #nombredatos=str(currentday.year)+"-"+str(currentday.month)+"-"+str(currentday.day)+"sfuData.csv"
    nombredatos=str(currentday.year)+"-"+str(currentday.month)+"-"+str(currentday.day)+"-"+str(currentday.hour)+"sfuData.csv"
    try:
        myFile = open(str(nombredatos), 'w',newline='')
        with myFile:
                writer = csv.writer(myFile)
                writer.writerows(listaDatos)

    finally:
        myFile.close()



# Cell
def main():
    datosSfu=[]
    sourcecode=getHTMLsfu()
    datosSfu=getDatosSfu(sourcecode)
    sfuScv(datosSfu)



# Cell
if __name__=="__main__":
    main()
