# AUTOGENERATED! DO NOT EDIT! File to edit: 00_web_scraping.ipynb (unless otherwise specified).

__all__ = ['getHTMLsfu', 'back', 'getCredentials', 'getInfo', 'getDatosSfu', 'sfuScv', 'web_scraping', 'main']

# Cell
import random
from time import sleep
from selenium import webdriver
from selenium.webdriver.firefox.options import Options
import datetime
import re
import csv
import os
from fastcore.script import *

# Cell
def getHTMLsfu():

    source_code=""
    try:
        rutadriver=back()
        rutadriver=str(rutadriver)+"geckodriver"
        #rutadriver=
        options = Options()
        options.add_argument('-headless')
        driver = webdriver.Firefox(executable_path=str(rutadriver), options=options)
        currentday = datetime.datetime.now()
        #driver.get("https://esc.cbk.waw.pl/products/api.php?parameter=f10_7&start_date=2019%2F01%2F01+00%3A00&end_date="+str(currentday.year)+"%2F"+str(currentday.month)+"%2F"+str(currentday.day)+"+00%3A00&output_type=html")
        driver.get("https://esc.cbk.waw.pl/products/api.php?parameter=f10_7&start_date="+str(currentday.year-1)+"%2F"+str(currentday.month)+"%2F"+str(currentday.day)+"+00%3A00&end_date="+str(currentday.year)+"%2F"+str(currentday.month)+"%2F"+str(currentday.day)+"+00%3A00&output_type=html")
        #driver.get("https://esc.cbk.waw.pl/products/api.php?parameter=f10_7&start_date=1750%2F01%2F01+00%3A00&end_date="+str(currentday.year)+"%2F"+str(currentday.month)+"%2F"+str(currentday.day)+"+00%3A00&output_type=html")
        sleep(random.uniform(8.0,10.0))


        user = driver.find_element_by_name("callback_0")
        password = driver.find_element_by_name("callback_1")
        button = driver.find_element_by_name("callback_2")

        credentials=getCredentials()
        user.send_keys(credentials[0])
        password.send_keys(credentials[1])
        button.click()
        sleep(random.uniform(10.0,12.0))

        elem = driver.find_element_by_xpath("//*")
        source_code = elem.get_attribute("outerHTML")

    finally:
        driver.quit()
    return source_code




# Cell
def back():
    path=os.getcwd()
    s=path.split('/')
    length=len(s)
    back_path=""
    for pathpart in range(0,length-1):
        if pathpart==0:
            back_path=s[pathpart]+"/"
        else:
            back_path=back_path+s[pathpart]+"/"
    return str(back_path)



# Cell
def getCredentials():
    credentials=[]
    user=getInfo("usuario")
    password=getInfo("password")
    credentials.append(user)
    credentials.append(password)
    return credentials


# Cell
def getInfo(element):
    try:
        rutatxt=back()
        rutatxt=str(rutatxt)+"/infouser.txt"
        f = open (rutatxt,'r')
        mensaje = f.read()
        info=re.findall(str(element)+"='(.*?)'",mensaje)[0]
    finally:
        f.close()
    return info

# Cell
def getDatosSfu(html):
    sfudiario=re.findall('<tr>\n<td>(.*?)/td></tr>',str(html),re.DOTALL)
    listaDatos=[]
    for dia in sfudiario:
        datofecha=re.findall("(.*?)</td>",dia)
        datosfu=re.findall("<td>(.*?)<",dia)
        listaDatos.append([datofecha[0],datosfu[0]])
    return listaDatos

# Cell
def sfuScv(listaDatos):
    currentday = datetime.datetime.now()
    #nombredatos=str(currentday.year)+"-"+str(currentday.month)+"-"+str(currentday.day)+"sfuData.csv"
    nombredatos=str(currentday.year)+"-"+str(currentday.month)+"-"+str(currentday.day)+"-"+str(currentday.hour)+"sfuData.csv"
    path=getInfo("csvdirectory")
    try:
        myFile = open(str(path)+str(nombredatos), 'w',newline='')
        with myFile:
                writer = csv.writer(myFile)
                writer.writerows(listaDatos)

    finally:
        myFile.close()



# Cell
def web_scraping():
    datosSfu=[]
    sourcecode=getHTMLsfu()
    datosSfu=getDatosSfu(sourcecode)
    sfuScv(datosSfu)


# Cell
@call_parse
def main():
    web_scraping()
