# AUTOGENERATED! DO NOT EDIT! File to edit: 01_weights_wandb.ipynb (unless otherwise specified).

__all__ = ['login', 'getInfo', 'back', 'downloadpth', 'loadmodel', 'main']

# Cell
import torch
import wandb
import os
import re
from fastcore.script import *

# Cell
def login():
    keywandb=getInfo("wandbkey")
    wandb.login(key=str(keywandb), relogin=True)

# Cell
def getInfo(element):
    try:
        rutatxt=back()
        rutatxt=str(rutatxt)+"/infouser.txt"
        #rutatxt=
        f = open (rutatxt,'r')
        mensaje = f.read()
        info=re.findall(str(element)+"='(.*?)'",mensaje)[0]
    finally:
        f.close()
    return info

# Cell
def back():
    path=os.getcwd()
    s=path.split('/')
    length=len(s)
    back_path=""
    for pathpart in range(0,length-1):
        if pathpart==0:
            back_path=s[pathpart]+"/"
        else:
            back_path=back_path+s[pathpart]+"/"
    return str(back_path)


# Cell
def downloadpth():
    api = wandb.Api()
    sweep = api.sweep("ecstevenson/swe_pytorch_ensemble/owfwgvb9")
    path= getInfo("pthdirectory")
    i=1
    for run in sweep.runs:
        pathfile=str(path)+str(i)+"/"
        i=1+i
        for file in run.files():
            if(file.name.find("best.pth")==0):
                file.download(pathfile,replace=True)
            if(file.name.find("config.yaml")==0):
                file.download(pathfile,replace=True)

# Cell
def loadmodel():
    login()
    downloadpth()

# Cell
@call_parse
def main():
    loadmodel()