# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/01_data.ipynb (unless otherwise specified).

__all__ = ['downloadpth', 'downloadmodel', 'main']

# Cell
import torch
import wandb
import os
import re
from fastcore.script import *
from .web_scraping import *

# Cell
def downloadpth(path,idsweep):
    api = wandb.Api()
    sweep = api.sweep(str(idsweep))
    runnumber=1
    horizon=-1
    for run in sweep.runs:
        #Comparamos el H anterior con el actual para resetear el contador de carpetas en caso de nuevo H
        if(horizon != run.config["horizon"]):
            runnumber=1
        else:
            runnumber=1+runnumber
        horizon=run.config["horizon"]
        pathHorizon=str(path)+"ensembleH"+str(horizon)
        pathfile=str(pathHorizon)+"/sweep_run_"+str(runnumber)+"/"

        for file in run.files():
            if(file.name.find("best.pth")==0):
                file.download(pathfile,replace=True)
            if(file.name.find("config.yaml")==0):
                file.download(pathfile,replace=True)


# Cell
def downloadmodel(path):
    ensembleH3 = "ecstevenson/swe_pytorch_ensemble/2c28yzhn"
    ensembleH5H7 = "ecstevenson/swe_pytorch_ensemble/6gkj1b5m"
    ensembleH10H14 = "ecstevenson/swe_pytorch_ensemble/0mhqqzhc"
    ensembleH21H27 = "ecstevenson/swe_pytorch_ensemble/oupg313c"
    downloadpth(path,ensembleH3)
    downloadpth(path,ensembleH5H7)
    downloadpth(path,ensembleH10H14)
    downloadpth(path,ensembleH21H27)


# Cell
@call_parse
def main():
    path= getInfo("pthdirectory")
    downloadmodel(path)