# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/01_download_model.ipynb (unless otherwise specified).

__all__ = ['getRunIds', 'downloadPth', 'downloadModel', 'main']

# Cell
import wandb
from fastcore.script import *
from .resources import getInfo

# Cell
def getRunIds(nametxt):
    pathfolderpth=getInfo("pthdirectory")
    datalist=[]
    try:

        with open(str(pathfolderpth)+str(nametxt), 'r') as myFile:
            try:
                datalist=[line.rstrip() for line in myFile]

                datalist.remove("ID")
                while('' in datalist):
                    datalist.remove('')
            finally:
                myFile.close()
    except (IOError, ValueError, EOFError) as e:
          print(e)
    return datalist

# Cell
def downloadPth(nametxt,savedirectory):
    api = wandb.Api()
    runs_id=getRunIds(nametxt)
    runnumber=1
    horizon=-1
    for run_id in runs_id:
            run =api.run("stardust-r/deep-learning-space-weather-forecasting/{}".format(run_id))
            #Comparamos el H anterior con el actual para resetear el contador de carpetas en caso de nuevo H
            if(horizon != run.config["horizon"]):
                runnumber=1
            else:
                runnumber=1+runnumber
            horizon=run.config['horizon']
            pathhorizon=str(savedirectory)+"ensembleH"+str(horizon)
            pathfile=str(pathhorizon)+"/sweep_run_"+str(runnumber)+"/"
            for file in run.files():
                if(file.name.find("config.yaml")==0):
                    file.download(pathfile,replace=True)
                if(file.name.find("models/best.pth")==0):
                    file.download(pathfile,replace=True)


# Cell
def downloadModel():
    path= getInfo("pthdirectory")
    ensemblerunids=["ensembleH3.txt","ensembleH5H7.txt","ensembleH10H14.txt","ensembleH21H27.txt"]

    for ensemble in ensemblerunids:
        print(ensemble)
        downloadPth(ensemble,path)

# Cell
@call_parse
def main():
    downloadModel()