# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/03_manage_data.ipynb (unless otherwise specified).

__all__ = ['NORMALIZE', 'HORIZONS', 'COLUMNS', 'savePredict', 'loadPredict', 'updatePredicts', 'doNewPredicts',
           'infoDatesPredicts']

# Cell
from .load_model import getAllHorizonPrediction
import datetime
import numpy as np
from .resources import getInfo
import csv
import pandas as pd
import pickle
from fastcore.script import * # @Callparser
NORMALIZE=707.6
HORIZONS=[3,5,7,10,14,21,27]
COLUMNS=['Date','H3','H5','H7','H10','H14','H21','H27']

# Cell
def savePredict(datalist):
    path=getInfo("csvdirectory")+"predictionData.csv"
    try:
        outfile  = open(path, 'wb')
        pickle.dump(datalist, outfile )
    finally:
        outfile.close()


# Cell
def loadPredict():
    predict= pd.DataFrame(columns=COLUMNS)
    path=getInfo("csvdirectory")+"predictionData.csv"
    try:
        with open(path,'rb') as infile:
            predict = pickle.load(infile, encoding='bytes')
        infile.close()
    except IOError:
        print("File not accessible")

    return predict

# Cell
@call_parse
def updatePredicts():
    path=getInfo("csvdirectory")+"predictionData.csv"
    datapredict=loadPredict()
    if(not datapredict.empty):
        yesterday = datetime.datetime.today().date()-datetime.timedelta(1)
        predictdate=pd.to_datetime(datapredict.loc[0,"Date"])+datetime.timedelta(1) #First date to predict

        if(yesterday >= predictdate):

            while(yesterday >= predictdate):# while yesterday is not in the past of data(predictdate)

                #print(predictdate,yesterday)
                print("Currently making ", predictdate.strftime("%Y-%m-%d") ," prediction")
                currentpredict=getAllHorizonPrediction(predictdate)
                datapredict=pd.concat([pd.DataFrame(currentpredict,columns=COLUMNS), datapredict], ignore_index=True)
                predictdate=predictdate+datetime.timedelta(1)


            print("Updated to ",yesterday)
            savePredict(datapredict)
        else:
            print("It was already updated")
    else:
        print("The file does not exist, you should make predictions to update")

# Cell
def doNewPredicts(days):
    datapredict=loadPredict()


    if(not datapredict.empty):
        datestart=pd.to_datetime(datapredict.iloc[-1].Date)-datetime.timedelta(1)
    else:
        datestart=datetime.datetime.now().replace(hour=0, minute=0, second=0, microsecond=0)-datetime.timedelta(1)
    for numdays in range(days):
        print((datestart-datetime.timedelta(numdays)).strftime("%Y-%m-%d"))
        currentpredict=getAllHorizonPrediction(datestart-datetime.timedelta(numdays))
        datapredict=pd.concat([datapredict,pd.DataFrame(currentpredict,columns=COLUMNS)], ignore_index=True)
        print("updated")
        savePredict(datapredict)

# Cell
def infoDatesPredicts():
    startdate=None
    enddate=None
    datapredict=loadPredict()
    if(not datapredict.empty):
        startdate=pd.to_datetime(datapredict.iloc[0].Date)
        enddate=pd.to_datetime(datapredict.iloc[-1].Date)
    return startdate,enddate